version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/app/"
    schedule:
      interval: "daily"
    allow:
      - dependency-type: "all"
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
